# `synthmed` demo

A minimal notebook that exercises the `synthmed` package end-to-end.
It contains **no business logic** — every step delegates to the package.

All inputs now live under `inputs/`:

- `inputs/schemas/<cohort>/<year>/*.fts` — schema files (committed).
- `inputs/distributions/` — reference distributions (committed; see
  `docs/distributions/` for per-file provenance).
- `inputs/samples/` — CMS DE-SynPUF inpatient sample CSVs
  (~320 MB, **not committed**; lazy-downloaded on first run, or
  populate manually with `synthmed download-samples`).

In [8]:
from pathlib import Path

from synthmed import GenerationConfig, load_distributions, run

REPO_ROOT = Path.cwd().parent

## 1. Configure the run

In [9]:
config = GenerationConfig(
    data_root=REPO_ROOT / "inputs" / "schemas",
    distribution_dir=REPO_ROOT / "inputs" / "distributions",
    # First run will lazy-download the ~320 MB DE-SynPUF samples from CMS
    # into this directory (or set SYNTHMED_OFFLINE=1 to disable that and
    # populate the directory manually). See docs/distributions/medicare_sample_data.md
    sample_dir=REPO_ROOT / "inputs" / "samples",
    output_dir=REPO_ROOT / "output_dat_files",
    total_people=1000,
)
config

GenerationConfig(data_root=WindowsPath('C:/Users/Mark/synthetic-resdac-claims/inputs/schemas'), distribution_dir=WindowsPath('C:/Users/Mark/synthetic-resdac-claims/inputs/distributions'), sample_dir=WindowsPath('C:/Users/Mark/synthetic-resdac-claims/inputs/samples'), output_dir=WindowsPath('C:/Users/Mark/synthetic-resdac-claims/output_dat_files'), total_people=1000, alive_ratio=0.95, average_medpar_records=0.267, new_year_new_patients_mean=0.05, new_year_new_patients_sd=0.005, initial_dob_start=1940, initial_dob_end=1950, overall_error_rate=0.006600000000000001, race_error_rate=0.85, dob_error_rate=0.11, no_medpar_error_rate=0.01, new_enrollment_no_medpar_rate=0.009, max_diag_columns=25, sampled_diag_columns=10, seed=None)

## 2. (Optional) inspect the reference distributions

Loading distributions explicitly lets us peek at them before running the
pipeline; `run(config)` would otherwise load them for us.

In [10]:
dist = load_distributions(config.distribution_dir, config.sample_dir)
dist.state_error_medpar.head()

   SSA Code  Error Rate
0         1        0.01
1         2        0.01
2         3        0.01
3         4        0.01
4         5        0.01

## 3. Run the full multi-year pipeline

Produces `.dat` files in `config.output_dir`, mirroring the
`<cohort>/<year>/` layout of `config.data_root`, and copies the matching
`.fts` schemas next to them.

In [11]:
directory_map = run(config, dist=dist)
sorted(directory_map.keys())

995
RangeIndex(start=0, stop=995, step=1)

C:\Users\Mark\synthetic-resdac-claims\src\synthmed\internal_db.py:77: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(base["death_date"], errors="coerce")

['%s', '%04d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%03d', '%03d', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s']
995
RangeIndex(start=0, stop=995, step=1)
['%s', '%04d', '%s', '%02d', '%02d', '%02d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s']
282
RangeIndex(start=0, stop=282, step=1)
BENE_ID
MEDPARID
MEDPAR_YR_NUM
CLM_TYPE
BIC
EQ_BIC
AGE_CNT
SEX
RACE
MS_CD
STATE_CD
CNTY_CD
BENE_ZIP
DSCHRGCD
FICARR
WRNGCD
GHOPDCD
PPS_IND
ORGNPINM
PRVDRNUM
SPCLUNIT
SSLSSNF
ACTV_XREF_IND
SLCT_RSN_CD
FACLMCNT
ACRTNDT
EXHST_DT
QLFYFROM
QLFYTHRU
SRC_ADMS
TYPE_ADM
ADMSNDAY
ADMSNDT
DSCHRGDT
DSTNTNCD
CVRLVLDT
DEATHDT
DEATHCD
DEATHDAY
SSICD
SSIDAY
INTRNL_USE_SSI_DATA
IPSBCD
FILDTCD
SMPLSIZE
LOSCNT
OUTLRDAY
UTIL_DAY
COIN_DAY
LRD_USE
COIN_AMT
DED_AMT
BLDDEDAM
PRPAY_CD
PRPAYAMT
DRG_CD
OUTLR_CD
OUTLRAMT
DRGPRICE
DISP_SHR
IME_AMT
PASSTHRU
PPS_CPTL
IP_LOW_VOL_PYMT_AMT
TOTCHRG
CVRCHRG
PMT_AMT
ACMDTNS
DPRTMNTL
PRVTDAY
SPRVTDAY
WARDDAY
ICARECNT
CRNRYDAY
PRVTAMT
SPRVTAMT
WARDAMT
ICAREAMT
CRNRYAMT
OTHRAMT
PHRMCAMT
SUPLYAMT
DME_AMT
UDME_AMT
PHYTHAMT
OCPTLAMT
SPCH_AMT
INHLTAMT
BLOODAMT
BLDADMIN
BLDFRNSH
OROOMAMT
LTHTRPSY
CRDLGY
ANSTHSA
LAB_AMT
RDLGYAMT
MRI_AMT
OPSRVC
ER_AMT
AMBLNC
PROFFEES
ORGNAMT
ESRDSETG
CLNC_AMT
ICUINDCD
CRNRY_CD
PHRMCYCD
TRNSPLNT
ONCLGYSW
DGNSTCSW
THRPTCSW
NUCLR_SW
CTSCANSW
IMGNG_SW
OPSRVCCD
ORGNCD
ESRD_CD
ESRDSTG1
ESRDSTG2
ESRDSTG3
ESRDSTG4
ESRDSTG5
AD_DGNS
ADMTG_DGNS_VRSN_CD
DGNSCNT
DGNS_VRSN_CD
DGNS_VRSN_CD_1
DGNS_VRSN_CD_2
DGNS_VRSN_CD_3
DGNS_VRSN_CD_4
DGNS_VRSN_CD_5
DGNS_VRSN_CD_6
DGNS_VRSN_CD_7
DGNS_VRSN_CD_8
DGNS_VRSN_CD_9
DGNS_VRSN_CD_10
DGNS_VRSN_CD_11
DGNS_VRSN_CD_12
DGNS_VRSN_CD_13
DGNS_VRSN_CD_14
DGNS_VRSN_CD_15
DGNS_VRSN_CD_16
DGNS_VRSN_CD_17
DGNS_VRSN_CD_18
DGNS_VRSN_CD_19
DGNS_VRSN_CD_20
DGNS_VRSN_CD_21
DGNS_VRSN_CD_22
DGNS_VRSN_CD_23
DGNS_VRSN_CD_24
DGNS_VRSN_CD_25
DGNSCD1
DGNSCD2
DGNSCD3
DGNSCD4
DGNSCD5
DGNSCD6
DGNSCD7
DGNSCD8
DGNSCD9
DGNSCD10
DGNSCD11
DGNSCD12
DGNSCD13
DGNSCD14
DGNSCD15
DGNSCD16
DGNSCD17
DGNSCD18
DGNSCD19
DGNSCD20
DGNSCD21
DGNSCD22
DGNSCD23
DGNSCD24
DGNSCD25
DGNS_POA
POA_DGNS_CD_CNT
POA_DGNS_1_IND_CD
POA_DGNS_2_IND_CD
POA_DGNS_3_IND_CD
POA_DGNS_4_IND_CD
POA_DGNS_5_IND_CD
POA_DGNS_6_IND_CD
POA_DGNS_7_IND_CD
POA_DGNS_8_IND_CD
POA_DGNS_9_IND_CD
POA_DGNS_10_IND_CD
POA_DGNS_11_IND_CD
POA_DGNS_12_IND_CD
POA_DGNS_13_IND_CD
POA_DGNS_14_IND_CD
POA_DGNS_15_IND_CD
POA_DGNS_16_IND_CD
POA_DGNS_17_IND_CD
POA_DGNS_18_IND_CD
POA_DGNS_19_IND_CD
POA_DGNS_20_IND_CD
POA_DGNS_21_IND_CD
POA_DGNS_22_IND_CD
POA_DGNS_23_IND_CD
POA_DGNS_24_IND_CD
POA_DGNS_25_IND_CD
DGNS_E_CD_CNT
DGNS_E_VRSN_CD
DGNS_E_VRSN_CD_1
DGNS_E_VRSN_CD_2
DGNS_E_VRSN_CD_3
DGNS_E_VRSN_CD_4
DGNS_E_VRSN_CD_5
DGNS_E_VRSN_CD_6
DGNS_E_VRSN_CD_7
DGNS_E_VRSN_CD_8
DGNS_E_VRSN_CD_9
DGNS_E_VRSN_CD_10
DGNS_E_VRSN_CD_11
DGNS_E_VRSN_CD_12
DGNS_E_1_CD
DGNS_E_2_CD
DGNS_E_3_CD
DGNS_E_4_CD
DGNS_E_5_CD
DGNS_E_6_CD
DGNS_E_7_CD
DGNS_E_8_CD
DGNS_E_9_CD
DGNS_E_10_CD
DGNS_E_11_CD
DGNS_E_12_CD
POA_DGNS_E_CD_CNT
POA_DGNS_E_1_IND_CD
POA_DGNS_E_2_IND_CD
POA_DGNS_E_3_IND_CD
POA_DGNS_E_4_IND_CD
POA_DGNS_E_5_IND_CD
POA_DGNS_E_6_IND_CD
POA_DGNS_E_7_IND_CD
POA_DGNS_E_8_IND_CD
POA_DGNS_E_9_IND_CD
POA_DGNS_E_10_IND_CD
POA_DGNS_E_11_IND_CD
POA_DGNS_E_12_IND_CD
PRCDRSW
PRCDRCNT
SRGCL_PRCDR_VRSN_CD
SRGCL_PRCDR_VRSN_CD_1
SRGCL_PRCDR_VRSN_CD_2
SRGCL_PRCDR_VRSN_CD_3
SRGCL_PRCDR_VRSN_CD_4
SRGCL_PRCDR_VRSN_CD_5
SRGCL_PRCDR_VRSN_CD_6
SRGCL_PRCDR_VRSN_CD_7
SRGCL_PRCDR_VRSN_CD_8
SRGCL_PRCDR_VRSN_CD_9
SRGCL_PRCDR_VRSN_CD_10
SRGCL_PRCDR_VRSN_CD_11
SRGCL_PRCDR_VRSN_CD_12
SRGCL_PRCDR_VRSN_CD_13
SRGCL_PRCDR_VRSN_CD_14
SRGCL_PRCDR_VRSN_CD_15
SRGCL_PRCDR_VRSN_CD_16
SRGCL_PRCDR_VRSN_CD_17
SRGCL_PRCDR_VRSN_CD_18
SRGCL_PRCDR_VRSN_CD_19
SRGCL_PRCDR_VRSN_CD_20
SRGCL_PRCDR_VRSN_CD_21
SRGCL_PRCDR_VRSN_CD_22
SRGCL_PRCDR_VRSN_CD_23
SRGCL_PRCDR_VRSN_CD_24
SRGCL_PRCDR_VRSN_CD_25
PRCDRCD1
PRCDRCD2
PRCDRCD3
PRCDRCD4
PRCDRCD5
PRCDRCD6
PRCDRCD7
PRCDRCD8
PRCDRCD9
PRCDRCD10
PRCDRCD11
PRCDRCD12
PRCDRCD13
PRCDRCD14
PRCDRCD15
PRCDRCD16
PRCDRCD17
PRCDRCD18
PRCDRCD19
PRCDRCD20
PRCDRCD21
PRCDRCD22
PRCDRCD23
PRCDRCD24
PRCDRCD25
PRCDTCNT
PRCDRDT1
PRCDRDT2
PRCDRDT3
PRCDRDT4
PRCDRDT5
PRCDRDT6
PRCDRDT7
PRCDRDT8
PRCDRDT9
PRCDRDT10
PRCDRDT11
PRCDRDT12
PRCDRDT13
PRCDRDT14
PRCDRDT15
PRCDRDT16
PRCDRDT17
PRCDRDT18
PRCDRDT19
PRCDRDT20
PRCDRDT21
PRCDRDT22
PRCDRDT23
PRCDRDT24
PRCDRDT25
CLM_PTNT_RLTNSHP_CD
CARE_IMPRVMT_MODEL_1_CD
CARE_IMPRVMT_MODEL_2_CD
CARE_IMPRVMT_MODEL_3_CD
CARE_IMPRVMT_MODEL_4_CD
VBP_PRTCPNT_IND_CD
HRR_PRTCPNT_IND_CD
BNDLD_MODEL_DSCNT_PCT
VBP_ADJSTMT_PCT
HRR_ADJSTMT_PCT
INFRMTL_ENCTR_IND_SW
MA_TCHNG_IND_SW
PROD_RPLCMT_LIFECYC_SW
PROD_RPLCMT_RCLL_SW
CRED_RCVD_RPLCD_DVC_SW
OBSRVTN_SW
NEW_TCHNLGY_ADD_ON_AMT
BASE_OPRTG_DRG_AMT
OPRTG_HSP_AMT
MDCL_SRGCL_GNRL_AMT
MDCL_SRGCL_NSTRL_AMT
MDCL_SRGCL_STRL_AMT
TAKE_HOME_AMT
PRSTHTC_ORTHTC_AMT
MDCL_SRGCL_PCMKR_AMT
INTRAOCULAR_LENS_AMT
OXYGN_TAKE_HOME_AMT
OTHR_IMPLANTS_AMT
OTHR_SUPLIES_DVC_AMT
INCDNT_RDLGY_AMT
INCDNT_DGNSTC_SRVCS_AMT
MDCL_SRGCL_DRSNG_AMT
INVSTGTNL_DVC_AMT
MDCL_SRGCL_MISC_AMT
RDLGY_ONCOLOGY_AMT
RDLGY_DGNSTC_AMT
RDLGY_THRPTC_AMT
RDLGY_NUCLR_MDCN_AMT
RDLGY_CT_SCAN_AMT
RDLGY_OTHR_IMGNG_AMT
OPRTG_ROOM_AMT
OR_LABOR_DLVRY_AMT
CRDC_CATHRZTN_AMT
['%s', '%s', '%04d', '%s', '%s', '%s', '%04d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%010d', '%010d', '%s', '%s', '%s', '%s', '%05d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%07d', '%s', '%07d', '%s', '%s', '%s', '%s', '%07d', '%05d', '%07d', '%05d', '%05d', '%010d', '%010d', '%010d', '%s', '%010d', '%s', '%s', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%05d', '%05d', '%05d', '%05d', '%05d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%05d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%.2f', '%.11f', '%.4f', '%s', '%s', '%s', '%s', '%s', '%s', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d']
incrementing internal database
45
after delta
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

C:\Users\Mark\synthetic-resdac-claims\src\synthmed\internal_db.py:77: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(base["death_date"], errors="coerce")

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
995
RangeIndex(start=0, stop=995, step=1)
['%s', '%04d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%03d', '%03d', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s']
995
RangeIndex(start=0, stop=995, step=1)
['%s', '%04d', '%s', '%02d', '%02d', '%02d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s']
279
RangeIndex(start=0, stop=279, step=1)
BENE_ID
MEDPARID
MEDPAR_YR_NUM
CLM_TYPE
BIC
EQ_BIC
AGE_CNT
SEX
RACE
MS_CD
STATE_CD
CNTY_CD
BENE_ZIP
DSCHRGCD
FICARR
WRNGCD
GHOPDCD
PPS_IND
ORGNPINM
PRVDRNUM
SPCLUNIT
SSLSSNF
ACTV_XREF_IND
SLCT_RSN_CD
FACLMCNT
ACRTNDT
EXHST_DT
QLFYFROM
QLFYTHRU
SRC_ADMS
TYPE_ADM
ADMSNDAY
ADMSNDT
DSCHRGDT
DSTNTNCD
CVRLVLDT
DEATHDT
DEATHCD
DEATHDAY
SSICD
SSIDAY
INTRNL_USE_SSI_DATA
IPSBCD
FILDTCD
SMPLSIZE
LOSCNT
OUTLRDAY
UTIL_DAY
COIN_DAY
LRD_USE
COIN_AMT
DED_AMT
BLDDEDAM
PRPAY_CD
PRPAYAMT
DRG_CD
OUTLR_CD
OUTLRAMT
DRGPRICE
DISP_SHR
IME_AMT
PASSTHRU
PPS_CPTL
IP_LOW_VOL_PYMT_AMT
TOTCHRG
CVRCHRG
PMT_AMT
ACMDTNS
DPRTMNTL
PRVTDAY
SPRVTDAY
WARDDAY
ICARECNT
CRNRYDAY
PRVTAMT
SPRVTAMT
WARDAMT
ICAREAMT
CRNRYAMT
OTHRAMT
PHRMCAMT
SUPLYAMT
DME_AMT
UDME_AMT
PHYTHAMT
OCPTLAMT
SPCH_AMT
INHLTAMT
BLOODAMT
BLDADMIN
BLDFRNSH
OROOMAMT
LTHTRPSY
CRDLGY
ANSTHSA
LAB_AMT
RDLGYAMT
MRI_AMT
OPSRVC
ER_AMT
AMBLNC
PROFFEES
ORGNAMT
ESRDSETG
CLNC_AMT
ICUINDCD
CRNRY_CD
PHRMCYCD
TRNSPLNT
ONCLGYSW
DGNSTCSW
THRPTCSW
NUCLR_SW
CTSCANSW
IMGNG_SW
OPSRVCCD
ORGNCD
ESRD_CD
ESRDSTG1
ESRDSTG2
ESRDSTG3
ESRDSTG4
ESRDSTG5
AD_DGNS
ADMTG_DGNS_VRSN_CD
DGNSCNT
DGNS_VRSN_CD
DGNS_VRSN_CD_1
DGNS_VRSN_CD_2
DGNS_VRSN_CD_3
DGNS_VRSN_CD_4
DGNS_VRSN_CD_5
DGNS_VRSN_CD_6
DGNS_VRSN_CD_7
DGNS_VRSN_CD_8
DGNS_VRSN_CD_9
DGNS_VRSN_CD_10
DGNS_VRSN_CD_11
DGNS_VRSN_CD_12
DGNS_VRSN_CD_13
DGNS_VRSN_CD_14
DGNS_VRSN_CD_15
DGNS_VRSN_CD_16
DGNS_VRSN_CD_17
DGNS_VRSN_CD_18
DGNS_VRSN_CD_19
DGNS_VRSN_CD_20
DGNS_VRSN_CD_21
DGNS_VRSN_CD_22
DGNS_VRSN_CD_23
DGNS_VRSN_CD_24
DGNS_VRSN_CD_25
DGNSCD1
DGNSCD2
DGNSCD3
DGNSCD4
DGNSCD5
DGNSCD6
DGNSCD7
DGNSCD8
DGNSCD9
DGNSCD10
DGNSCD11
DGNSCD12
DGNSCD13
DGNSCD14
DGNSCD15
DGNSCD16
DGNSCD17
DGNSCD18
DGNSCD19
DGNSCD20
DGNSCD21
DGNSCD22
DGNSCD23
DGNSCD24
DGNSCD25
DGNS_POA
POA_DGNS_CD_CNT
POA_DGNS_1_IND_CD
POA_DGNS_2_IND_CD
POA_DGNS_3_IND_CD
POA_DGNS_4_IND_CD
POA_DGNS_5_IND_CD
POA_DGNS_6_IND_CD
POA_DGNS_7_IND_CD
POA_DGNS_8_IND_CD
POA_DGNS_9_IND_CD
POA_DGNS_10_IND_CD
POA_DGNS_11_IND_CD
POA_DGNS_12_IND_CD
POA_DGNS_13_IND_CD
POA_DGNS_14_IND_CD
POA_DGNS_15_IND_CD
POA_DGNS_16_IND_CD
POA_DGNS_17_IND_CD
POA_DGNS_18_IND_CD
POA_DGNS_19_IND_CD
POA_DGNS_20_IND_CD
POA_DGNS_21_IND_CD
POA_DGNS_22_IND_CD
POA_DGNS_23_IND_CD
POA_DGNS_24_IND_CD
POA_DGNS_25_IND_CD
DGNS_E_CD_CNT
DGNS_E_VRSN_CD
DGNS_E_VRSN_CD_1
DGNS_E_VRSN_CD_2
DGNS_E_VRSN_CD_3
DGNS_E_VRSN_CD_4
DGNS_E_VRSN_CD_5
DGNS_E_VRSN_CD_6
DGNS_E_VRSN_CD_7
DGNS_E_VRSN_CD_8
DGNS_E_VRSN_CD_9
DGNS_E_VRSN_CD_10
DGNS_E_VRSN_CD_11
DGNS_E_VRSN_CD_12
DGNS_E_1_CD
DGNS_E_2_CD
DGNS_E_3_CD
DGNS_E_4_CD
DGNS_E_5_CD
DGNS_E_6_CD
DGNS_E_7_CD
DGNS_E_8_CD
DGNS_E_9_CD
DGNS_E_10_CD
DGNS_E_11_CD
DGNS_E_12_CD
POA_DGNS_E_CD_CNT
POA_DGNS_E_1_IND_CD
POA_DGNS_E_2_IND_CD
POA_DGNS_E_3_IND_CD
POA_DGNS_E_4_IND_CD
POA_DGNS_E_5_IND_CD
POA_DGNS_E_6_IND_CD
POA_DGNS_E_7_IND_CD
POA_DGNS_E_8_IND_CD
POA_DGNS_E_9_IND_CD
POA_DGNS_E_10_IND_CD
POA_DGNS_E_11_IND_CD
POA_DGNS_E_12_IND_CD
PRCDRSW
PRCDRCNT
SRGCL_PRCDR_VRSN_CD
SRGCL_PRCDR_VRSN_CD_1
SRGCL_PRCDR_VRSN_CD_2
SRGCL_PRCDR_VRSN_CD_3
SRGCL_PRCDR_VRSN_CD_4
SRGCL_PRCDR_VRSN_CD_5
SRGCL_PRCDR_VRSN_CD_6
SRGCL_PRCDR_VRSN_CD_7
SRGCL_PRCDR_VRSN_CD_8
SRGCL_PRCDR_VRSN_CD_9
SRGCL_PRCDR_VRSN_CD_10
SRGCL_PRCDR_VRSN_CD_11
SRGCL_PRCDR_VRSN_CD_12
SRGCL_PRCDR_VRSN_CD_13
SRGCL_PRCDR_VRSN_CD_14
SRGCL_PRCDR_VRSN_CD_15
SRGCL_PRCDR_VRSN_CD_16
SRGCL_PRCDR_VRSN_CD_17
SRGCL_PRCDR_VRSN_CD_18
SRGCL_PRCDR_VRSN_CD_19
SRGCL_PRCDR_VRSN_CD_20
SRGCL_PRCDR_VRSN_CD_21
SRGCL_PRCDR_VRSN_CD_22
SRGCL_PRCDR_VRSN_CD_23
SRGCL_PRCDR_VRSN_CD_24
SRGCL_PRCDR_VRSN_CD_25
PRCDRCD1
PRCDRCD2
PRCDRCD3
PRCDRCD4
PRCDRCD5
PRCDRCD6
PRCDRCD7
PRCDRCD8
PRCDRCD9
PRCDRCD10
PRCDRCD11
PRCDRCD12
PRCDRCD13
PRCDRCD14
PRCDRCD15
PRCDRCD16
PRCDRCD17
PRCDRCD18
PRCDRCD19
PRCDRCD20
PRCDRCD21
PRCDRCD22
PRCDRCD23
PRCDRCD24
PRCDRCD25
PRCDTCNT
PRCDRDT1
PRCDRDT2
PRCDRDT3
PRCDRDT4
PRCDRDT5
PRCDRDT6
PRCDRDT7
PRCDRDT8
PRCDRDT9
PRCDRDT10
PRCDRDT11
PRCDRDT12
PRCDRDT13
PRCDRDT14
PRCDRDT15
PRCDRDT16
PRCDRDT17
PRCDRDT18
PRCDRDT19
PRCDRDT20
PRCDRDT21
PRCDRDT22
PRCDRDT23
PRCDRDT24
PRCDRDT25
CLM_PTNT_RLTNSHP_CD
CARE_IMPRVMT_MODEL_1_CD
CARE_IMPRVMT_MODEL_2_CD
CARE_IMPRVMT_MODEL_3_CD
CARE_IMPRVMT_MODEL_4_CD
VBP_PRTCPNT_IND_CD
HRR_PRTCPNT_IND_CD
BNDLD_MODEL_DSCNT_PCT
VBP_ADJSTMT_PCT
HRR_ADJSTMT_PCT
INFRMTL_ENCTR_IND_SW
MA_TCHNG_IND_SW
PROD_RPLCMT_LIFECYC_SW
PROD_RPLCMT_RCLL_SW
CRED_RCVD_RPLCD_DVC_SW
OBSRVTN_SW
NEW_TCHNLGY_ADD_ON_AMT
BASE_OPRTG_DRG_AMT
OPRTG_HSP_AMT
MDCL_SRGCL_GNRL_AMT
MDCL_SRGCL_NSTRL_AMT
MDCL_SRGCL_STRL_AMT
TAKE_HOME_AMT
PRSTHTC_ORTHTC_AMT
MDCL_SRGCL_PCMKR_AMT
INTRAOCULAR_LENS_AMT
OXYGN_TAKE_HOME_AMT
OTHR_IMPLANTS_AMT
OTHR_SUPLIES_DVC_AMT
INCDNT_RDLGY_AMT
INCDNT_DGNSTC_SRVCS_AMT
MDCL_SRGCL_DRSNG_AMT
INVSTGTNL_DVC_AMT
MDCL_SRGCL_MISC_AMT
RDLGY_ONCOLOGY_AMT
RDLGY_DGNSTC_AMT
RDLGY_THRPTC_AMT
RDLGY_NUCLR_MDCN_AMT
RDLGY_CT_SCAN_AMT
RDLGY_OTHR_IMGNG_AMT
OPRTG_ROOM_AMT
OR_LABOR_DLVRY_AMT
CRDC_CATHRZTN_AMT
['%s', '%s', '%04d', '%s', '%s', '%s', '%04d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%010d', '%010d', '%s', '%s', '%s', '%s', '%05d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%07d', '%s', '%07d', '%s', '%s', '%s', '%s', '%07d', '%05d', '%07d', '%05d', '%05d', '%010d', '%010d', '%010d', '%s', '%010d', '%s', '%s', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%05d', '%05d', '%05d', '%05d', '%05d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%05d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%.2f', '%.11f', '%.4f', '%s', '%s', '%s', '%s', '%s', '%s', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d']
incrementing internal database
54
after delta
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
951
RangeIndex(start=0, stop=951, step=1)
['%s', '%04d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%03d', '%03d', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s']
951
RangeIndex(start=0, stop=951, step=1)
['%s', '%04d', '%s', '%02d', '%02d', '%02d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s']
245
RangeIndex(start=0, stop=245, step=1)
BENE_ID
MEDPARID
MEDPAR_YR_NUM
CLM_TYPE
BIC
EQ_BIC
AGE_CNT
SEX
RACE
MS_CD
STATE_CD
CNTY_CD
BENE_ZIP
DSCHRGCD
FICARR
WRNGCD
GHOPDCD
PPS_IND
ORGNPINM
PRVDRNUM
SPCLUNIT
SSLSSNF
ACTV_XREF_IND
SLCT_RSN_CD
FACLMCNT
ACRTNDT
EXHST_DT
QLFYFROM
QLFYTHRU
SRC_ADMS
TYPE_ADM
ADMSNDAY
ADMSNDT
DSCHRGDT
DSTNTNCD
CVRLVLDT
DEATHDT
DEATHCD
DEATHDAY
SSICD
SSIDAY
INTRNL_USE_SSI_DATA
IPSBCD
FILDTCD
SMPLSIZE
LOSCNT
OUTLRDAY
UTIL_DAY
COIN_DAY
LRD_USE
COIN_AMT
DED_AMT
BLDDEDAM
PRPAY_CD
PRPAYAMT
DRG_CD
OUTLR_CD
OUTLRAMT
DRGPRICE
DISP_SHR
IME_AMT
PASSTHRU
PPS_CPTL
IP_LOW_VOL_PYMT_AMT
TOTCHRG
CVRCHRG
PMT_AMT
ACMDTNS
DPRTMNTL
PRVTDAY
SPRVTDAY
WARDDAY
ICARECNT
CRNRYDAY
PRVTAMT
SPRVTAMT
WARDAMT
ICAREAMT
CRNRYAMT
OTHRAMT
PHRMCAMT
SUPLYAMT
DME_AMT
UDME_AMT
PHYTHAMT
OCPTLAMT
SPCH_AMT
INHLTAMT
BLOODAMT
BLDADMIN
BLDFRNSH
OROOMAMT
LTHTRPSY
CRDLGY
ANSTHSA
LAB_AMT
RDLGYAMT
MRI_AMT
OPSRVC
ER_AMT
AMBLNC
PROFFEES
ORGNAMT
ESRDSETG
CLNC_AMT
ICUINDCD
CRNRY_CD
PHRMCYCD
TRNSPLNT
ONCLGYSW
DGNSTCSW
THRPTCSW
NUCLR_SW
CTSCANSW
IMGNG_SW
OPSRVCCD
ORGNCD
ESRD_CD
ESRDSTG1
ESRDSTG2
ESRDSTG3
ESRDSTG4
ESRDSTG5
AD_DGNS
ADMTG_DGNS_VRSN_CD
DGNSCNT
DGNS_VRSN_CD
DGNS_VRSN_CD_1
DGNS_VRSN_CD_2
DGNS_VRSN_CD_3
DGNS_VRSN_CD_4
DGNS_VRSN_CD_5
DGNS_VRSN_CD_6
DGNS_VRSN_CD_7
DGNS_VRSN_CD_8
DGNS_VRSN_CD_9
DGNS_VRSN_CD_10
DGNS_VRSN_CD_11
DGNS_VRSN_CD_12
DGNS_VRSN_CD_13
DGNS_VRSN_CD_14
DGNS_VRSN_CD_15
DGNS_VRSN_CD_16
DGNS_VRSN_CD_17
DGNS_VRSN_CD_18
DGNS_VRSN_CD_19
DGNS_VRSN_CD_20
DGNS_VRSN_CD_21
DGNS_VRSN_CD_22
DGNS_VRSN_CD_23
DGNS_VRSN_CD_24
DGNS_VRSN_CD_25
DGNSCD1
DGNSCD2
DGNSCD3
DGNSCD4
DGNSCD5
DGNSCD6
DGNSCD7
DGNSCD8
DGNSCD9
DGNSCD10
DGNSCD11
DGNSCD12
DGNSCD13
DGNSCD14
DGNSCD15
DGNSCD16
DGNSCD17
DGNSCD18
DGNSCD19
DGNSCD20
DGNSCD21
DGNSCD22
DGNSCD23
DGNSCD24
DGNSCD25
DGNS_POA
POA_DGNS_CD_CNT
POA_DGNS_1_IND_CD
POA_DGNS_2_IND_CD
POA_DGNS_3_IND_CD
POA_DGNS_4_IND_CD
POA_DGNS_5_IND_CD
POA_DGNS_6_IND_CD
POA_DGNS_7_IND_CD
POA_DGNS_8_IND_CD
POA_DGNS_9_IND_CD
POA_DGNS_10_IND_CD
POA_DGNS_11_IND_CD
POA_DGNS_12_IND_CD
POA_DGNS_13_IND_CD
POA_DGNS_14_IND_CD
POA_DGNS_15_IND_CD
POA_DGNS_16_IND_CD
POA_DGNS_17_IND_CD
POA_DGNS_18_IND_CD
POA_DGNS_19_IND_CD
POA_DGNS_20_IND_CD
POA_DGNS_21_IND_CD
POA_DGNS_22_IND_CD
POA_DGNS_23_IND_CD
POA_DGNS_24_IND_CD
POA_DGNS_25_IND_CD
DGNS_E_CD_CNT
DGNS_E_VRSN_CD
DGNS_E_VRSN_CD_1
DGNS_E_VRSN_CD_2
DGNS_E_VRSN_CD_3
DGNS_E_VRSN_CD_4
DGNS_E_VRSN_CD_5
DGNS_E_VRSN_CD_6
DGNS_E_VRSN_CD_7
DGNS_E_VRSN_CD_8
DGNS_E_VRSN_CD_9
DGNS_E_VRSN_CD_10
DGNS_E_VRSN_CD_11
DGNS_E_VRSN_CD_12
DGNS_E_1_CD
DGNS_E_2_CD
DGNS_E_3_CD
DGNS_E_4_CD
DGNS_E_5_CD
DGNS_E_6_CD
DGNS_E_7_CD
DGNS_E_8_CD
DGNS_E_9_CD
DGNS_E_10_CD
DGNS_E_11_CD
DGNS_E_12_CD
POA_DGNS_E_CD_CNT
POA_DGNS_E_1_IND_CD
POA_DGNS_E_2_IND_CD
POA_DGNS_E_3_IND_CD
POA_DGNS_E_4_IND_CD
POA_DGNS_E_5_IND_CD
POA_DGNS_E_6_IND_CD
POA_DGNS_E_7_IND_CD
POA_DGNS_E_8_IND_CD
POA_DGNS_E_9_IND_CD
POA_DGNS_E_10_IND_CD
POA_DGNS_E_11_IND_CD
POA_DGNS_E_12_IND_CD
PRCDRSW
PRCDRCNT
SRGCL_PRCDR_VRSN_CD
SRGCL_PRCDR_VRSN_CD_1
SRGCL_PRCDR_VRSN_CD_2
SRGCL_PRCDR_VRSN_CD_3
SRGCL_PRCDR_VRSN_CD_4
SRGCL_PRCDR_VRSN_CD_5
SRGCL_PRCDR_VRSN_CD_6
SRGCL_PRCDR_VRSN_CD_7
SRGCL_PRCDR_VRSN_CD_8
SRGCL_PRCDR_VRSN_CD_9
SRGCL_PRCDR_VRSN_CD_10
SRGCL_PRCDR_VRSN_CD_11
SRGCL_PRCDR_VRSN_CD_12
SRGCL_PRCDR_VRSN_CD_13
SRGCL_PRCDR_VRSN_CD_14
SRGCL_PRCDR_VRSN_CD_15
SRGCL_PRCDR_VRSN_CD_16
SRGCL_PRCDR_VRSN_CD_17
SRGCL_PRCDR_VRSN_CD_18
SRGCL_PRCDR_VRSN_CD_19
SRGCL_PRCDR_VRSN_CD_20
SRGCL_PRCDR_VRSN_CD_21
SRGCL_PRCDR_VRSN_CD_22
SRGCL_PRCDR_VRSN_CD_23
SRGCL_PRCDR_VRSN_CD_24
SRGCL_PRCDR_VRSN_CD_25
PRCDRCD1
PRCDRCD2
PRCDRCD3
PRCDRCD4
PRCDRCD5
PRCDRCD6
PRCDRCD7
PRCDRCD8
PRCDRCD9
PRCDRCD10
PRCDRCD11
PRCDRCD12
PRCDRCD13
PRCDRCD14
PRCDRCD15
PRCDRCD16
PRCDRCD17
PRCDRCD18
PRCDRCD19
PRCDRCD20
PRCDRCD21
PRCDRCD22
PRCDRCD23
PRCDRCD24
PRCDRCD25
PRCDTCNT
PRCDRDT1
PRCDRDT2
PRCDRDT3
PRCDRDT4
PRCDRDT5
PRCDRDT6
PRCDRDT7
PRCDRDT8
PRCDRDT9
PRCDRDT10
PRCDRDT11
PRCDRDT12
PRCDRDT13
PRCDRDT14
PRCDRDT15
PRCDRDT16
PRCDRDT17
PRCDRDT18
PRCDRDT19
PRCDRDT20
PRCDRDT21
PRCDRDT22
PRCDRDT23
PRCDRDT24
PRCDRDT25
CLM_PTNT_RLTNSHP_CD
CARE_IMPRVMT_MODEL_1_CD
CARE_IMPRVMT_MODEL_2_CD
CARE_IMPRVMT_MODEL_3_CD
CARE_IMPRVMT_MODEL_4_CD
VBP_PRTCPNT_IND_CD
HRR_PRTCPNT_IND_CD
BNDLD_MODEL_DSCNT_PCT
VBP_ADJSTMT_PCT
HRR_ADJSTMT_PCT
INFRMTL_ENCTR_IND_SW
MA_TCHNG_IND_SW
PROD_RPLCMT_LIFECYC_SW
PROD_RPLCMT_RCLL_SW
CRED_RCVD_RPLCD_DVC_SW
OBSRVTN_SW
NEW_TCHNLGY_ADD_ON_AMT
BASE_OPRTG_DRG_AMT
OPRTG_HSP_AMT
MDCL_SRGCL_GNRL_AMT
MDCL_SRGCL_NSTRL_AMT
MDCL_SRGCL_STRL_AMT
TAKE_HOME_AMT
PRSTHTC_ORTHTC_AMT
MDCL_SRGCL_PCMKR_AMT
INTRAOCULAR_LENS_AMT
OXYGN_TAKE_HOME_AMT
OTHR_IMPLANTS_AMT
OTHR_SUPLIES_DVC_AMT
INCDNT_RDLGY_AMT
INCDNT_DGNSTC_SRVCS_AMT
MDCL_SRGCL_DRSNG_AMT
INVSTGTNL_DVC_AMT
MDCL_SRGCL_MISC_AMT
RDLGY_ONCOLOGY_AMT
RDLGY_DGNSTC_AMT
RDLGY_THRPTC_AMT
RDLGY_NUCLR_MDCN_AMT
RDLGY_CT_SCAN_AMT
RDLGY_OTHR_IMGNG_AMT
OPRTG_ROOM_AMT
OR_LABOR_DLVRY_AMT
CRDC_CATHRZTN_AMT
SQSTRTN_RDCTN_AMT
UNCOMPD_CARE_PYMT_AMT
BNDLD_ADJSTMT_AMT
VBP_ADJSTMT_AMT
HRR_ADJSTMT_AMT
['%s', '%s', '%04d', '%s', '%s', '%s', '%04d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%010d', '%010d', '%s', '%s', '%s', '%s', '%05d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%07d', '%s', '%07d', '%s', '%s', '%s', '%s', '%07d', '%05d', '%07d', '%05d', '%05d', '%010d', '%010d', '%010d', '%s', '%010d', '%s', '%s', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%05d', '%05d', '%05d', '%05d', '%05d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%05d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%.2f', '%.11f', '%.4f', '%s', '%s', '%s', '%s', '%s', '%s', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d']
incrementing internal database
44
after delta
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

C:\Users\Mark\synthetic-resdac-claims\src\synthmed\internal_db.py:77: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(base["death_date"], errors="coerce")

0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
831
RangeIndex(start=0, stop=831, step=1)
['%s', '%04d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%03d', '%03d', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s']
831
RangeIndex(start=0, stop=831, step=1)
['%s', '%04d', '%s', '%02d', '%02d', '%02d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s']
232
RangeIndex(start=0, stop=232, step=1)
BENE_ID
MEDPARID
MEDPAR_YR_NUM
CLM_TYPE
BIC
EQ_BIC
AGE_CNT
SEX
RACE
MS_CD
STATE_CD
CNTY_CD
BENE_ZIP
DSCHRGCD
FICARR
WRNGCD
GHOPDCD
PPS_IND
ORGNPINM
PRVDRNUM
SPCLUNIT
SSLSSNF
ACTV_XREF_IND
SLCT_RSN_CD
FACLMCNT
ACRTNDT
EXHST_DT
QLFYFROM
QLFYTHRU
SRC_ADMS
TYPE_ADM
ADMSNDAY
ADMSNDT
DSCHRGDT
DSTNTNCD
CVRLVLDT
DEATHDT
DEATHCD
DEATHDAY
SSICD
SSIDAY
INTRNL_USE_SSI_DATA
IPSBCD
FILDTCD
SMPLSIZE
LOSCNT
OUTLRDAY
UTIL_DAY
COIN_DAY
LRD_USE
COIN_AMT
DED_AMT
BLDDEDAM
PRPAY_CD
PRPAYAMT
DRG_CD
OUTLR_CD
OUTLRAMT
DRGPRICE
DISP_SHR
IME_AMT
PASSTHRU
PPS_CPTL
IP_LOW_VOL_PYMT_AMT
TOTCHRG
CVRCHRG
PMT_AMT
ACMDTNS
DPRTMNTL
PRVTDAY
SPRVTDAY
WARDDAY
ICARECNT
CRNRYDAY
PRVTAMT
SPRVTAMT
WARDAMT
ICAREAMT
CRNRYAMT
OTHRAMT
PHRMCAMT
SUPLYAMT
DME_AMT
UDME_AMT
PHYTHAMT
OCPTLAMT
SPCH_AMT
INHLTAMT
BLOODAMT
BLDADMIN
BLDFRNSH
OROOMAMT
LTHTRPSY
CRDLGY
ANSTHSA
LAB_AMT
RDLGYAMT
MRI_AMT
OPSRVC
ER_AMT
AMBLNC
PROFFEES
ORGNAMT
ESRDSETG
CLNC_AMT
ICUINDCD
CRNRY_CD
PHRMCYCD
TRNSPLNT
ONCLGYSW
DGNSTCSW
THRPTCSW
NUCLR_SW
CTSCANSW
IMGNG_SW
OPSRVCCD
ORGNCD
ESRD_CD
ESRDSTG1
ESRDSTG2
ESRDSTG3
ESRDSTG4
ESRDSTG5
AD_DGNS
ADMTG_DGNS_VRSN_CD
DGNSCNT
DGNS_VRSN_CD
DGNS_VRSN_CD_1
DGNS_VRSN_CD_2
DGNS_VRSN_CD_3
DGNS_VRSN_CD_4
DGNS_VRSN_CD_5
DGNS_VRSN_CD_6
DGNS_VRSN_CD_7
DGNS_VRSN_CD_8
DGNS_VRSN_CD_9
DGNS_VRSN_CD_10
DGNS_VRSN_CD_11
DGNS_VRSN_CD_12
DGNS_VRSN_CD_13
DGNS_VRSN_CD_14
DGNS_VRSN_CD_15
DGNS_VRSN_CD_16
DGNS_VRSN_CD_17
DGNS_VRSN_CD_18
DGNS_VRSN_CD_19
DGNS_VRSN_CD_20
DGNS_VRSN_CD_21
DGNS_VRSN_CD_22
DGNS_VRSN_CD_23
DGNS_VRSN_CD_24
DGNS_VRSN_CD_25
DGNSCD1
DGNSCD2
DGNSCD3
DGNSCD4
DGNSCD5
DGNSCD6
DGNSCD7
DGNSCD8
DGNSCD9
DGNSCD10
DGNSCD11
DGNSCD12
DGNSCD13
DGNSCD14
DGNSCD15
DGNSCD16
DGNSCD17
DGNSCD18
DGNSCD19
DGNSCD20
DGNSCD21
DGNSCD22
DGNSCD23
DGNSCD24
DGNSCD25
DGNS_POA
POA_DGNS_CD_CNT
POA_DGNS_1_IND_CD
POA_DGNS_2_IND_CD
POA_DGNS_3_IND_CD
POA_DGNS_4_IND_CD
POA_DGNS_5_IND_CD
POA_DGNS_6_IND_CD
POA_DGNS_7_IND_CD
POA_DGNS_8_IND_CD
POA_DGNS_9_IND_CD
POA_DGNS_10_IND_CD
POA_DGNS_11_IND_CD
POA_DGNS_12_IND_CD
POA_DGNS_13_IND_CD
POA_DGNS_14_IND_CD
POA_DGNS_15_IND_CD
POA_DGNS_16_IND_CD
POA_DGNS_17_IND_CD
POA_DGNS_18_IND_CD
POA_DGNS_19_IND_CD
POA_DGNS_20_IND_CD
POA_DGNS_21_IND_CD
POA_DGNS_22_IND_CD
POA_DGNS_23_IND_CD
POA_DGNS_24_IND_CD
POA_DGNS_25_IND_CD
DGNS_E_CD_CNT
DGNS_E_VRSN_CD
DGNS_E_VRSN_CD_1
DGNS_E_VRSN_CD_2
DGNS_E_VRSN_CD_3
DGNS_E_VRSN_CD_4
DGNS_E_VRSN_CD_5
DGNS_E_VRSN_CD_6
DGNS_E_VRSN_CD_7
DGNS_E_VRSN_CD_8
DGNS_E_VRSN_CD_9
DGNS_E_VRSN_CD_10
DGNS_E_VRSN_CD_11
DGNS_E_VRSN_CD_12
DGNS_E_1_CD
DGNS_E_2_CD
DGNS_E_3_CD
DGNS_E_4_CD
DGNS_E_5_CD
DGNS_E_6_CD
DGNS_E_7_CD
DGNS_E_8_CD
DGNS_E_9_CD
DGNS_E_10_CD
DGNS_E_11_CD
DGNS_E_12_CD
POA_DGNS_E_CD_CNT
POA_DGNS_E_1_IND_CD
POA_DGNS_E_2_IND_CD
POA_DGNS_E_3_IND_CD
POA_DGNS_E_4_IND_CD
POA_DGNS_E_5_IND_CD
POA_DGNS_E_6_IND_CD
POA_DGNS_E_7_IND_CD
POA_DGNS_E_8_IND_CD
POA_DGNS_E_9_IND_CD
POA_DGNS_E_10_IND_CD
POA_DGNS_E_11_IND_CD
POA_DGNS_E_12_IND_CD
PRCDRSW
PRCDRCNT
SRGCL_PRCDR_VRSN_CD
SRGCL_PRCDR_VRSN_CD_1
SRGCL_PRCDR_VRSN_CD_2
SRGCL_PRCDR_VRSN_CD_3
SRGCL_PRCDR_VRSN_CD_4
SRGCL_PRCDR_VRSN_CD_5
SRGCL_PRCDR_VRSN_CD_6
SRGCL_PRCDR_VRSN_CD_7
SRGCL_PRCDR_VRSN_CD_8
SRGCL_PRCDR_VRSN_CD_9
SRGCL_PRCDR_VRSN_CD_10
SRGCL_PRCDR_VRSN_CD_11
SRGCL_PRCDR_VRSN_CD_12
SRGCL_PRCDR_VRSN_CD_13
SRGCL_PRCDR_VRSN_CD_14
SRGCL_PRCDR_VRSN_CD_15
SRGCL_PRCDR_VRSN_CD_16
SRGCL_PRCDR_VRSN_CD_17
SRGCL_PRCDR_VRSN_CD_18
SRGCL_PRCDR_VRSN_CD_19
SRGCL_PRCDR_VRSN_CD_20
SRGCL_PRCDR_VRSN_CD_21
SRGCL_PRCDR_VRSN_CD_22
SRGCL_PRCDR_VRSN_CD_23
SRGCL_PRCDR_VRSN_CD_24
SRGCL_PRCDR_VRSN_CD_25
PRCDRCD1
PRCDRCD2
PRCDRCD3
PRCDRCD4
PRCDRCD5
PRCDRCD6
PRCDRCD7
PRCDRCD8
PRCDRCD9
PRCDRCD10
PRCDRCD11
PRCDRCD12
PRCDRCD13
PRCDRCD14
PRCDRCD15
PRCDRCD16
PRCDRCD17
PRCDRCD18
PRCDRCD19
PRCDRCD20
PRCDRCD21
PRCDRCD22
PRCDRCD23
PRCDRCD24
PRCDRCD25
PRCDTCNT
PRCDRDT1
PRCDRDT2
PRCDRDT3
PRCDRDT4
PRCDRDT5
PRCDRDT6
PRCDRDT7
PRCDRDT8
PRCDRDT9
PRCDRDT10
PRCDRDT11
PRCDRDT12
PRCDRDT13
PRCDRDT14
PRCDRDT15
PRCDRDT16
PRCDRDT17
PRCDRDT18
PRCDRDT19
PRCDRDT20
PRCDRDT21
PRCDRDT22
PRCDRDT23
PRCDRDT24
PRCDRDT25
CLM_PTNT_RLTNSHP_CD
CARE_IMPRVMT_MODEL_1_CD
CARE_IMPRVMT_MODEL_2_CD
CARE_IMPRVMT_MODEL_3_CD
CARE_IMPRVMT_MODEL_4_CD
VBP_PRTCPNT_IND_CD
HRR_PRTCPNT_IND_CD
BNDLD_MODEL_DSCNT_PCT
VBP_ADJSTMT_PCT
HRR_ADJSTMT_PCT
INFRMTL_ENCTR_IND_SW
MA_TCHNG_IND_SW
PROD_RPLCMT_LIFECYC_SW
PROD_RPLCMT_RCLL_SW
CRED_RCVD_RPLCD_DVC_SW
OBSRVTN_SW
NEW_TCHNLGY_ADD_ON_AMT
BASE_OPRTG_DRG_AMT
OPRTG_HSP_AMT
MDCL_SRGCL_GNRL_AMT
MDCL_SRGCL_NSTRL_AMT
MDCL_SRGCL_STRL_AMT
TAKE_HOME_AMT
PRSTHTC_ORTHTC_AMT
MDCL_SRGCL_PCMKR_AMT
INTRAOCULAR_LENS_AMT
OXYGN_TAKE_HOME_AMT
OTHR_IMPLANTS_AMT
OTHR_SUPLIES_DVC_AMT
INCDNT_RDLGY_AMT
INCDNT_DGNSTC_SRVCS_AMT
MDCL_SRGCL_DRSNG_AMT
INVSTGTNL_DVC_AMT
MDCL_SRGCL_MISC_AMT
RDLGY_ONCOLOGY_AMT
RDLGY_DGNSTC_AMT
RDLGY_THRPTC_AMT
RDLGY_NUCLR_MDCN_AMT
RDLGY_CT_SCAN_AMT
RDLGY_OTHR_IMGNG_AMT
OPRTG_ROOM_AMT
OR_LABOR_DLVRY_AMT
CRDC_CATHRZTN_AMT
SQSTRTN_RDCTN_AMT
UNCOMPD_CARE_PYMT_AMT
BNDLD_ADJSTMT_AMT
VBP_ADJSTMT_AMT
HRR_ADJSTMT_AMT
EHR_PYMT_ADJSTMT_AMT
PPS_STD_VAL_PYMT_AMT
FINL_STD_AMT
IPPS_FLEX_PYMT_6_AMT
IPPS_FLEX_PYMT_7_AMT
PTNT_ADD_ON_PYMT_AMT
HAC_PGM_RDCTN_IND_SW
PGM_RDCTN_IND_SW
PA_IND_CD
UNIQ_TRKNG_NUM
STAY_2_IND_SW
['%s', '%s', '%04d', '%s', '%s', '%s', '%04d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%010d', '%010d', '%s', '%s', '%s', '%s', '%05d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%07d', '%s', '%07d', '%s', '%s', '%s', '%s', '%07d', '%05d', '%07d', '%05d', '%05d', '%010d', '%010d', '%010d', '%s', '%010d', '%s', '%s', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%05d', '%05d', '%05d', '%05d', '%05d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%05d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%.5f', '%.13f', '%.6f', '%s', '%s', '%s', '%s', '%s', '%s', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%s', '%s', '%s', '%014d', '%s']
incrementing internal database
43
after delta
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

C:\Users\Mark\synthetic-resdac-claims\src\synthmed\internal_db.py:77: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(base["death_date"], errors="coerce")

0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
874
RangeIndex(start=0, stop=874, step=1)
['%s', '%04d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%03d', '%03d', '%03d', '%03d', '%03d', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s']
216
RangeIndex(start=0, stop=216, step=1)
BENE_ID
MEDPARID
MEDPAR_YR_NUM
CLM_TYPE
BIC
EQ_BIC
AGE_CNT
SEX
RACE
MS_CD
STATE_CD
CNTY_CD
BENE_ZIP
DSCHRGCD
FICARR
WRNGCD
GHOPDCD
PPS_IND
ORGNPINM
PRVDRNUM
SPCLUNIT
SSLSSNF
ACTV_XREF_IND
SLCT_RSN_CD
FACLMCNT
ACRTNDT
EXHST_DT
QLFYFROM
QLFYTHRU
SRC_ADMS
TYPE_ADM
ADMSNDAY
ADMSNDT
DSCHRGDT
DSTNTNCD
CVRLVLDT
DEATHDT
DEATHCD
DEATHDAY
SSICD
SSIDAY
INTRNL_USE_SSI_DATA
IPSBCD
FILDTCD
SMPLSIZE
LOSCNT
OUTLRDAY
UTIL_DAY
COIN_DAY
LRD_USE
COIN_AMT
DED_AMT
BLDDEDAM
PRPAY_CD
PRPAYAMT
DRG_CD
OUTLR_CD
OUTLRAMT
DRGPRICE
DISP_SHR
IME_AMT
PASSTHRU
PPS_CPTL
IP_LOW_VOL_PYMT_AMT
TOTCHRG
CVRCHRG
PMT_AMT
ACMDTNS
DPRTMNTL
PRVTDAY
SPRVTDAY
WARDDAY
ICARECNT
CRNRYDAY
PRVTAMT
SPRVTAMT
WARDAMT
ICAREAMT
CRNRYAMT
OTHRAMT
PHRMCAMT
SUPLYAMT
DME_AMT
UDME_AMT
PHYTHAMT
OCPTLAMT
SPCH_AMT
INHLTAMT
BLOODAMT
BLDADMIN
BLDFRNSH
OROOMAMT
LTHTRPSY
CRDLGY
ANSTHSA
LAB_AMT
RDLGYAMT
MRI_AMT
OPSRVC
ER_AMT
AMBLNC
PROFFEES
ORGNAMT
ESRDSETG
CLNC_AMT
ICUINDCD
CRNRY_CD
PHRMCYCD
TRNSPLNT
ONCLGYSW
DGNSTCSW
THRPTCSW
NUCLR_SW
CTSCANSW
IMGNG_SW
OPSRVCCD
ORGNCD
ESRD_CD
ESRDSTG1
ESRDSTG2
ESRDSTG3
ESRDSTG4
ESRDSTG5
AD_DGNS
ADMTG_DGNS_VRSN_CD
DGNSCNT
DGNS_VRSN_CD
DGNS_VRSN_CD_1
DGNS_VRSN_CD_2
DGNS_VRSN_CD_3
DGNS_VRSN_CD_4
DGNS_VRSN_CD_5
DGNS_VRSN_CD_6
DGNS_VRSN_CD_7
DGNS_VRSN_CD_8
DGNS_VRSN_CD_9
DGNS_VRSN_CD_10
DGNS_VRSN_CD_11
DGNS_VRSN_CD_12
DGNS_VRSN_CD_13
DGNS_VRSN_CD_14
DGNS_VRSN_CD_15
DGNS_VRSN_CD_16
DGNS_VRSN_CD_17
DGNS_VRSN_CD_18
DGNS_VRSN_CD_19
DGNS_VRSN_CD_20
DGNS_VRSN_CD_21
DGNS_VRSN_CD_22
DGNS_VRSN_CD_23
DGNS_VRSN_CD_24
DGNS_VRSN_CD_25
DGNSCD1
DGNSCD2
DGNSCD3
DGNSCD4
DGNSCD5
DGNSCD6
DGNSCD7
DGNSCD8
DGNSCD9
DGNSCD10
DGNSCD11
DGNSCD12
DGNSCD13
DGNSCD14
DGNSCD15
DGNSCD16
DGNSCD17
DGNSCD18
DGNSCD19
DGNSCD20
DGNSCD21
DGNSCD22
DGNSCD23
DGNSCD24
DGNSCD25
DGNS_POA
POA_DGNS_CD_CNT
POA_DGNS_1_IND_CD
POA_DGNS_2_IND_CD
POA_DGNS_3_IND_CD
POA_DGNS_4_IND_CD
POA_DGNS_5_IND_CD
POA_DGNS_6_IND_CD
POA_DGNS_7_IND_CD
POA_DGNS_8_IND_CD
POA_DGNS_9_IND_CD
POA_DGNS_10_IND_CD
POA_DGNS_11_IND_CD
POA_DGNS_12_IND_CD
POA_DGNS_13_IND_CD
POA_DGNS_14_IND_CD
POA_DGNS_15_IND_CD
POA_DGNS_16_IND_CD
POA_DGNS_17_IND_CD
POA_DGNS_18_IND_CD
POA_DGNS_19_IND_CD
POA_DGNS_20_IND_CD
POA_DGNS_21_IND_CD
POA_DGNS_22_IND_CD
POA_DGNS_23_IND_CD
POA_DGNS_24_IND_CD
POA_DGNS_25_IND_CD
DGNS_E_CD_CNT
DGNS_E_VRSN_CD
DGNS_E_VRSN_CD_1
DGNS_E_VRSN_CD_2
DGNS_E_VRSN_CD_3
DGNS_E_VRSN_CD_4
DGNS_E_VRSN_CD_5
DGNS_E_VRSN_CD_6
DGNS_E_VRSN_CD_7
DGNS_E_VRSN_CD_8
DGNS_E_VRSN_CD_9
DGNS_E_VRSN_CD_10
DGNS_E_VRSN_CD_11
DGNS_E_VRSN_CD_12
DGNS_E_1_CD
DGNS_E_2_CD
DGNS_E_3_CD
DGNS_E_4_CD
DGNS_E_5_CD
DGNS_E_6_CD
DGNS_E_7_CD
DGNS_E_8_CD
DGNS_E_9_CD
DGNS_E_10_CD
DGNS_E_11_CD
DGNS_E_12_CD
POA_DGNS_E_CD_CNT
POA_DGNS_E_1_IND_CD
POA_DGNS_E_2_IND_CD
POA_DGNS_E_3_IND_CD
POA_DGNS_E_4_IND_CD
POA_DGNS_E_5_IND_CD
POA_DGNS_E_6_IND_CD
POA_DGNS_E_7_IND_CD
POA_DGNS_E_8_IND_CD
POA_DGNS_E_9_IND_CD
POA_DGNS_E_10_IND_CD
POA_DGNS_E_11_IND_CD
POA_DGNS_E_12_IND_CD
PRCDRSW
PRCDRCNT
SRGCL_PRCDR_VRSN_CD
SRGCL_PRCDR_VRSN_CD_1
SRGCL_PRCDR_VRSN_CD_2
SRGCL_PRCDR_VRSN_CD_3
SRGCL_PRCDR_VRSN_CD_4
SRGCL_PRCDR_VRSN_CD_5
SRGCL_PRCDR_VRSN_CD_6
SRGCL_PRCDR_VRSN_CD_7
SRGCL_PRCDR_VRSN_CD_8
SRGCL_PRCDR_VRSN_CD_9
SRGCL_PRCDR_VRSN_CD_10
SRGCL_PRCDR_VRSN_CD_11
SRGCL_PRCDR_VRSN_CD_12
SRGCL_PRCDR_VRSN_CD_13
SRGCL_PRCDR_VRSN_CD_14
SRGCL_PRCDR_VRSN_CD_15
SRGCL_PRCDR_VRSN_CD_16
SRGCL_PRCDR_VRSN_CD_17
SRGCL_PRCDR_VRSN_CD_18
SRGCL_PRCDR_VRSN_CD_19
SRGCL_PRCDR_VRSN_CD_20
SRGCL_PRCDR_VRSN_CD_21
SRGCL_PRCDR_VRSN_CD_22
SRGCL_PRCDR_VRSN_CD_23
SRGCL_PRCDR_VRSN_CD_24
SRGCL_PRCDR_VRSN_CD_25
PRCDRCD1
PRCDRCD2
PRCDRCD3
PRCDRCD4
PRCDRCD5
PRCDRCD6
PRCDRCD7
PRCDRCD8
PRCDRCD9
PRCDRCD10
PRCDRCD11
PRCDRCD12
PRCDRCD13
PRCDRCD14
PRCDRCD15
PRCDRCD16
PRCDRCD17
PRCDRCD18
PRCDRCD19
PRCDRCD20
PRCDRCD21
PRCDRCD22
PRCDRCD23
PRCDRCD24
PRCDRCD25
PRCDTCNT
PRCDRDT1
PRCDRDT2
PRCDRDT3
PRCDRDT4
PRCDRDT5
PRCDRDT6
PRCDRDT7
PRCDRDT8
PRCDRDT9
PRCDRDT10
PRCDRDT11
PRCDRDT12
PRCDRDT13
PRCDRDT14
PRCDRDT15
PRCDRDT16
PRCDRDT17
PRCDRDT18
PRCDRDT19
PRCDRDT20
PRCDRDT21
PRCDRDT22
PRCDRDT23
PRCDRDT24
PRCDRDT25
CLM_PTNT_RLTNSHP_CD
CARE_IMPRVMT_MODEL_1_CD
CARE_IMPRVMT_MODEL_2_CD
CARE_IMPRVMT_MODEL_3_CD
CARE_IMPRVMT_MODEL_4_CD
VBP_PRTCPNT_IND_CD
HRR_PRTCPNT_IND_CD
BNDLD_MODEL_DSCNT_PCT
VBP_ADJSTMT_PCT
HRR_ADJSTMT_PCT
INFRMTL_ENCTR_IND_SW
MA_TCHNG_IND_SW
PROD_RPLCMT_LIFECYC_SW
PROD_RPLCMT_RCLL_SW
CRED_RCVD_RPLCD_DVC_SW
OBSRVTN_SW
NEW_TCHNLGY_ADD_ON_AMT
BASE_OPRTG_DRG_AMT
OPRTG_HSP_AMT
MDCL_SRGCL_GNRL_AMT
MDCL_SRGCL_NSTRL_AMT
MDCL_SRGCL_STRL_AMT
TAKE_HOME_AMT
PRSTHTC_ORTHTC_AMT
MDCL_SRGCL_PCMKR_AMT
INTRAOCULAR_LENS_AMT
OXYGN_TAKE_HOME_AMT
OTHR_IMPLANTS_AMT
OTHR_SUPLIES_DVC_AMT
INCDNT_RDLGY_AMT
INCDNT_DGNSTC_SRVCS_AMT
MDCL_SRGCL_DRSNG_AMT
INVSTGTNL_DVC_AMT
MDCL_SRGCL_MISC_AMT
RDLGY_ONCOLOGY_AMT
RDLGY_DGNSTC_AMT
RDLGY_THRPTC_AMT
RDLGY_NUCLR_MDCN_AMT
RDLGY_CT_SCAN_AMT
RDLGY_OTHR_IMGNG_AMT
OPRTG_ROOM_AMT
OR_LABOR_DLVRY_AMT
CRDC_CATHRZTN_AMT
SQSTRTN_RDCTN_AMT
UNCOMPD_CARE_PYMT_AMT
BNDLD_ADJSTMT_AMT
VBP_ADJSTMT_AMT
HRR_ADJSTMT_AMT
EHR_PYMT_ADJSTMT_AMT
PPS_STD_VAL_PYMT_AMT
FINL_STD_AMT
HAC_RDCTN_PMT_AMT
IPPS_FLEX_PYMT_7_AMT
PTNT_ADD_ON_PYMT_AMT
HAC_PGM_RDCTN_IND_SW
PGM_RDCTN_IND_SW
PA_IND_CD
UNIQ_TRKNG_NUM
STAY_2_IND_SW
CLM_SITE_NTRL_PYMT_CST_AMT
CLM_SITE_NTRL_PYMT_IPPS_AMT
CLM_FULL_STD_PYMT_AMT
CLM_SS_OUTLIER_STD_PYMT_AMT
CLM_NGACO_IND_1_CD
CLM_NGACO_IND_2_CD
CLM_NGACO_IND_3_CD
CLM_NGACO_IND_4_CD
CLM_NGACO_IND_5_CD
CLM_RSDL_PYMT_IND_CD
CLM_RP_IND_CD
RC_RP_IND_CD
ACO_ID_NUM
RC_ALLOGENEIC_STEM_CELL_AMT
ISLET_ADD_ON_PYMT_AMT
['%s', '%s', '%04d', '%s', '%s', '%s', '%04d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%010d', '%010d', '%s', '%s', '%s', '%s', '%05d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%07d', '%s', '%07d', '%s', '%s', '%s', '%s', '%07d', '%05d', '%07d', '%05d', '%05d', '%010d', '%010d', '%010d', '%s', '%010d', '%s', '%s', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%05d', '%05d', '%05d', '%05d', '%05d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%05d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%03d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%.5f', '%.13f', '%.6f', '%s', '%s', '%s', '%s', '%s', '%s', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%010d', '%s', '%s', '%s', '%014d', '%s', '%010d', '%010d', '%010d', '%010d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%010d', '%010d', '%010d']

['2011', '2012', '2013', '2014', '2016']

## 4. Spot-check an output file

In [12]:
first_year = sorted(directory_map.keys())[0]
out_dir = directory_map[first_year]["output"]
list(out_dir.iterdir())

[WindowsPath('C:/Users/Mark/synthetic-resdac-claims/output_dat_files/1111/2011/mbsf_ab_summary_resXXXXXXXX_reqXXXXXX_2011.dat'),
 WindowsPath('C:/Users/Mark/synthetic-resdac-claims/output_dat_files/1111/2011/mbsf_ab_summary_resXXXXXXXX_reqXXXXXX_2011.fts'),
 WindowsPath('C:/Users/Mark/synthetic-resdac-claims/output_dat_files/1111/2011/mbsf_d_cmpnts_resXXXXXXXX_reqXXXXXX_2011.dat'),
 WindowsPath('C:/Users/Mark/synthetic-resdac-claims/output_dat_files/1111/2011/mbsf_d_cmpnts_resXXXXXXXX_reqXXXXXX_2011.fts'),
 WindowsPath('C:/Users/Mark/synthetic-resdac-claims/output_dat_files/1111/2011/medpar_all_file_resXXXXXXXX_reqXXXXXX_2011.dat'),
 WindowsPath('C:/Users/Mark/synthetic-resdac-claims/output_dat_files/1111/2011/medpar_all_file_resXXXXXXXX_reqXXXXXX_2011.fts')]

## 5. Browse an output file as a DataFrame

Pick any `.dat` file under `output_dat_files/` and load it using the
matching `.fts` schema. Jupyter renders the resulting DataFrame as a
scrollable HTML table — the easiest way to inspect what was generated.

In [13]:
import os

import dorieh.cms.fts2yaml as f2y
import pandas as pd


def load_output(stem: str) -> pd.DataFrame:
    """Load an output `.dat` file as a DataFrame using its matching `.fts` schema.

    Pass the path with no extension; both `.dat` and `.fts` are appended.
    """
    fts = f2y.MedicareFTS(f2y.mcr_type(os.path.basename(stem) + ".fts")).init(stem + ".fts")
    n_real = int(fts.metadata["Columns in File"])
    cols = fts.columns[:n_real]
    return pd.read_fwf(
        stem + ".dat",
        widths=[int(c.width) for c in cols],
        names=[c.column for c in cols],
        dtype=str,
    )


stem = str(REPO_ROOT / "output_dat_files" / "4444" / "2016" / "mbsf_abcd_summary_resXXXXXXXX_reqXXXXXX_2016")
df = load_output(stem)
df

,BENE_ID,RFRNC_YR,ENRL_SRC,SAMPLE_GROUP,EFIVEPCT,CRNT_BIC,STATE_CD,CNTY_CD,ZIP_CD,STATE_CNTY_FIPS_CD_01,...,CSTSHR03,CSTSHR04,CSTSHR05,CSTSHR06,CSTSHR07,CSTSHR08,CSTSHR09,CSTSHR10,CSTSHR11,CSTSHR12
0,RJACNZTRDAMS001,2016,566,54,3,55,05,460,68552,460,...,60,73,03,63,73,06,79,38,99,50
1,RJACNZTRDAMS002,2016,703,98,4,79,44,930,65009,930,...,99,30,98,32,10,49,14,52,62,38
2,RJACNZTRDAMS003,2016,889,90,9,12,43,350,27381,350,...,54,04,05,11,97,40,31,25,15,41
3,RJACNZTRDAMS004,2016,600,47,6,54,10,120,27241,120,...,68,57,90,03,34,34,30,66,77,51
4,RJACNZTRDAMS007,2016,464,09,5,14,05,200,52111,200,...,43,22,95,66,11,06,00,88,64,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
869,HGCOSRHVXOZI038,2016,872,91,7,48,10,510,52165,510,...,41,68,71,61,16,60,08,57,33,92
870,HGCOSRHVXOZI039,2016,291,47,3,89,45,910,06355,910,...,13,19,01,40,89,17,53,17,97,10
871,HGCOSRHVXOZI040,2016,419,58,0,90,16,840,02958,840,...,48,30,24,75,99,63,78,31,28,82
872,HGCOSRHVXOZI041,2016,860,14,1,67,24,700,63231,700,...,79,97,26,58,88,35,99,27,77,17
873,HGCOSRHVXOZI042,2016,147,81,5,07,10,510,84384,510,...,62,57,03,26,06,96,92,68,53,44

### Focus on the HMO / Buy-In monthly columns

Filter the DataFrame down to BENE_ID plus the 12 monthly HMO and Buy-In
indicator columns. The current generation logic gives most beneficiaries
a flat 12-month pattern (all "0"/"3" for "not enrolled", all "C" for
"enrolled"), with ~1–4% in a sticky Markov walk over the remaining
codes.